import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css/pagination";
import { Pagination } from "swiper";
import { Navigation, Autoplay } from "swiper";
import "swiper/css";
import { useCallback, useRef } from "react";
import GridCard from "@/components/GridCard";
import SingleCard from "@/components/SingleCard";
export default function Home() {
  const swiperRef = useRef();

  const handlePrev = () => {
    swiperRef.current?.slidePrev();
  };

  const handleNext = () => {
    swiperRef.current?.slideNext();
  };

  return (
    <>
      <Head>
        <title>Amazon India</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <Header />
        <div className="page-content relative w-full h-screen">
          <div className="page-content-banner h-[360px] absolute w-full top-0 left-0 right-0">
            <button
              className="slider-left-btn absolute left-[23px] top-[99px] z-30"
              onClick={handlePrev}
            >
              <img src="/left_arrow.svg" alt="left-arrow" />
            </button>
            <button
              className="slider-right-btn absolute right-[23px] top-[99px] z-30"
              onClick={handleNext}
            >
              <img src="/right_arrow.svg" alt="right-arrow" />
            </button>

            <div className="absolute left-0 to-0">
              <div
                className="pointer-events-none psuedo-banner absolute w-full h-[350px] top-[250px] z-10"
                style={{
                  background: `linear-gradient(180deg, rgba(234, 237, 237, 0) 0%, #E3E6E6 100%)`,
                }}
              ></div>
              <div className="carousel-banner w-full z-10">
                <Swiper
                  className="mySwiper w-full"
                  slidesPerView={1}
                  spaceBetween={30}
                  modules={[Navigation, Autoplay]}
                  onBeforeInit={(swiper) => {
                    swiperRef.current = swiper;
                  }}
                  loop={true}
                  autoplay={{
                    delay: 2500,
                    disableOnInteraction: false,
                  }}
                >
                  <SwiperSlide>
                    <img
                      src="https://m.media-amazon.com/images/I/619rl+QqjwL._SX3000_.jpg"
                      alt="banner-1"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img src="/banner_1..png" alt="banner-1" />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src="https://m.media-amazon.com/images/I/61KpBiq7UKL._SX3000_.jpg"
                      alt="banner-1"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src="https://m.media-amazon.com/images/I/9124wfYc4-L._SX3000_.jpg"
                      alt="banner-1"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src="https://m.media-amazon.com/images/I/613-gA49v1L._SX3000_.jpg"
                      alt="banner-1"
                    />
                  </SwiperSlide>
                  <SwiperSlide>
                    <img
                      src="https://m.media-amazon.com/images/I/714A6e++fhL._SX3000_.jpg"
                      alt="banner-1"
                    />
                  </SwiperSlide>
                </Swiper>
              </div>
            </div>
          </div>
          <div className="page-content-products-layout absolute px-8  -top-[90px] sm:-top-[45px] md:top-[10px] lg:top-[150px] w-[98%] left-[50%] -translate-x-[50%] py-64 z-20 rounded-md">
            <section className="grid md:grid-cols-2 lg:grid-cols-4 w-full gap-6">
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 col-span-2 lg:col-span-3 w-full">
                <GridCard
                  title={"Up to 60% off | Styles for men"}
                  images={[
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-1-372-232._SY232_CB636110853_.jpg",
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-2-372-232._SY232_CB636110853_.jpg",
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-3-372-232._SY232_CB636110853_.jpg",
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF_4-372-232._SY232_CB636110853_.jpg",
                  ]}
                  categories={[
                    "Clothing",
                    "Footwear",
                    "Watches",
                    "Bags & Luggages",
                  ]}
                />
                <SingleCard
                  title="Up to 70% off | Clearance store"
                  image="https://images-eu.ssl-images-amazon.com/images/G/31/img22/Electronics/Clearance/Clearance_store_Desktop_CC_2x._SY608_CB628315133_.jpg"
                />
                <GridCard
                  title={"Starting ₹87 | Amazon Brands & more"}
                  images={[
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-1-372-232._SY232_CB636110853_.jpg",
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-2-372-232._SY232_CB636110853_.jpg",
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-3-372-232._SY232_CB636110853_.jpg",
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF_4-372-232._SY232_CB636110853_.jpg",
                  ]}
                  categories={[
                    "Clothing",
                    "Footwear",
                    "Watches",
                    "Bags & Luggages",
                  ]}
                />

                <GridCard
                  title={"Up to 60% off | Styles for men"}
                  images={[
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-1-372-232._SY232_CB636110853_.jpg",
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-2-372-232._SY232_CB636110853_.jpg",
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-3-372-232._SY232_CB636110853_.jpg",
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF_4-372-232._SY232_CB636110853_.jpg",
                  ]}
                  categories={[
                    "Clothing",
                    "Footwear",
                    "Watches",
                    "Bags & Luggages",
                  ]}
                />
                <SingleCard
                  title="Up to 70% off | Clearance store"
                  image="https://images-eu.ssl-images-amazon.com/images/G/31/img22/Electronics/Clearance/Clearance_store_Desktop_CC_2x._SY608_CB628315133_.jpg"
                />
                <GridCard
                  title={"Starting ₹87 | Amazon Brands & more"}
                  images={[
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-1-372-232._SY232_CB636110853_.jpg",
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-2-372-232._SY232_CB636110853_.jpg",
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-3-372-232._SY232_CB636110853_.jpg",
                    "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF_4-372-232._SY232_CB636110853_.jpg",
                  ]}
                  categories={[
                    "Clothing",
                    "Footwear",
                    "Watches",
                    "Bags & Luggages",
                  ]}
                />
              </div>
              <div className="col-span-2 lg:col-span-1 w-full">
                <div className="py-3 px-3 bg-white rounded-md w-full">
                  <h3 className="text-xl font-semibold">
                    Sign in for your best experience
                  </h3>
                  <button className="w-full h-[32px] bg-[#FFD814] rounded-md font-semibold mt-3 text-xs">
                    Sign in securely
                  </button>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}
